version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.10"

python:
  install:
    - requirements: requirements.txt

commands:
  - pip install -r requirements.txt
  - sphinx-apidoc -f -o docs/source/generated docs/hikerapi/hikerapi
  - sphinx-build -b html docs/source $READTHEDOCS_OUTPUT/html
